-- Look up which pokemon knows a certain move
SELECT PKMON_NAME, MOVESET_LEVEL FROM
(SELECT * FROM (SELECT * FROM MOVE JOIN MOVESET ON MOVESET.MOVESET_MOVE = MOVE.MOVE_NAME) T1 JOIN PKMON ON T1.MOVESET_PKMON = PKMON.PKMON_ID) T2
WHERE MOVE_NAME = 'Thunderbolt';