-- Find weaknesses and resistances of a pokemon
SET @pokemon = 'Bulbasaur';
SELECT TYPE_EFFECT_ATK , (T1.TYPE_EFFECT_DAMAGE * IF((SELECT COUNT(PKMON_SECTYPE) FROM pkmon WHERE PKMON_NAME = @pokemon) = 1, T2.TYPE_EFFECT_DAMAGE, 1)) AS COMBINED FROM 
(SELECT * FROM type_effect WHERE TYPE_EFFECT_DEF = (SELECT PKMON_TYPE FROM pkmon WHERE PKMON_NAME = @pokemon)) T1 JOIN
(SELECT * FROM type_effect WHERE TYPE_EFFECT_DEF = (SELECT IFNULL(PKMON_SECTYPE, PKMON_TYPE) FROM pkmon WHERE PKMON_NAME = @pokemon)) T2
USING (TYPE_EFFECT_ATK)
ORDER BY COMBINED DESC
